# Generated by Django 4.2.3 on 2023-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='clouds_all',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='feels_like',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='temp_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_deg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
