# Generated by Django 4.2.3 on 2023-07-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_weatherdata_clouds_all_weatherdata_feels_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20),
        ),
    ]
